particlesJS.load('particles-js','porfolio-config.json');var nav=document.querySelector('#nav');var landingLogo=document.querySelector('#landing-logo');var textChange=document.querySelector('.landing-text');function navToggle(){if(nav.classList.contains('opened')){nav.classList.remove('opened')}else{nav.classList.add('opened')}}var landingLogo=document.querySelector('#landing-logo');var textChange=document.querySelector('.landing-text');var tl=gsap.timeline();tl.to(landingLogo,{duration:1,delay:1,opacity:0,transformOrigin:"center"});tl.to(textChange,{duration:1,delay:0,opacity:0,transformOrigin:"center"});tl.to(textChange,{duration:1,delay:1,opacity:1,transformOrigin:"center"});if(!(landingLogo==null)){var changeTestimonials=setTimeout(()=>{textChange.style.top='20%';textChange.innerHTML=`
                <p>"${testimonials[0].body }"</p>
                <p class="testimonial-name"><strong> - ${testimonials[0].client }</strong></p>
                <img src="${testimonials[0].image }">`},4000)}const testimonials=[{client:'Clyde Everitt, Owner of Vollev Marketing (Pty) Ltd',body:`My company was is need of an updated and more professional website in order to attract more clients
                and generate more traffic through it to increase the exposure and grow the client base for the company.
                Abraham Thiao was tasked with this project and from the first meeting he was able to understand and
                identify with the what was required through the look and feel and the content of the site. His ability to
                provide a quick turn-around time with a strong attention to detail enabled us to have our site up and
                running as required in a short period of time.
                I can strongly recommend him and his professional ability to assist any clients requiring any form of web
                site design or enhancement, social media requirements or mobile application requirements, they will
                not be disappointed`,image:'https://media-exp1.licdn.com/dms/image/C5603AQGlYNcGe6yvRQ/profile-displayphoto-shrink_200_200/0/1517485149190?e=1611792000&v=beta&t=GnHH3YGaa_KdugyBqtac13nYK6ueySwJpsDe_BqIrQc'}]
                function pageTransition(){var tl=gsap.timeline();tl.to('.transition svg path',{duration:0.8,opacity:1,stagger:.05,rotationY:20,transformOrigin:"center"});tl.to('.transition svg path',{duration:1,rotation:0,opacity:0,stagger:.05});if(nav.classList.contains('opened')){navToggle()}}var mySwiper=new Swiper('.swiper-container',{pagination:{el:'.swiper-pagination',type:'bullets'},speed:400,spaceBetween:80,touchEventsTarget:'container'});function copyEmail(){var copyText=document.getElementById("myInput");let copyButt=document.querySelector(".copy-notif");copyText.select();copyText.setSelectionRange(0,25);document.execCommand("copy");copyButt.classList.add("copied");setTimeout(()=>{copyButt.classList.remove("copied")},5000)}function contanimation(){var tl=gsap.timeline()}function delay(n){n=n||2000;return new Promise(d=>{setTimeout(()=>{d()},n)})}barba.init({sync:true,transitions:[{async leave(data){const done=this.async;pageTransition();clearInterval(changeTestimonials);await delay(1000);done()},async enter(data){contanimation()}}]});barba.hooks.after(()=>{var mySwiper=new Swiper('.swiper-container',{pagination:{el:'.swiper-pagination',type:'bullets'},speed:400,spaceBetween:80,touchEventsTarget:'container'});let newStuffLogo=document.querySelector('#landing-logo');let newStuffLanding=document.querySelector('.landing-text');if(!(newStuffLogo==null)){var tl=gsap.timeline();tl.to(newStuffLogo,{duration:1,delay:1,opacity:0,transformOrigin:"center"});tl.to(newStuffLanding,{duration:1,delay:0,opacity:0,transformOrigin:"center"});tl.to(newStuffLanding,{duration:1,delay:1,opacity:1,transformOrigin:"center"});var changeTestimonials=setInterval(()=>{newStuffLanding.innerHTML=`
                <p>"${testimonials[0].body }"</p>
                <p class="testimonial-name"><strong> - ${testimonials[0].client }</strong></p>
                <img src="${testimonials[0].image }">`;newStuffLanding.style.top='20%'},4000)}});